from tkinter import *
def get_info():
    x = entry_name.get()
    print(x)

window = Tk()
bank_logo = PhotoImage(file='bank-building.PNG')
window.geometry("300x300")
window.title("Bank System")
label = Label(window,text="Welcome to the bank",height=2,image=bank_logo,side=BOTTOM)
account_name_label= Label(window, text="Account Name:")
account_number_label= Label(window, text="Account Number:")
entry_name = Entry(window)
entry_number = Entry(window)
submit_button = Button(text='submit',command=get_info)
exit_button = Button(text='exit',command=quit)
label.pack()
account_name_label.place(x=10, y=180)
account_number_label.place(x=10,y=200)
entry_name.place(x =120,y=180)
entry_number.place(x=120,y=200)
submit_button.place(x=100, y=250)
exit_button.place(x=160,y=250)
window.mainloop()